server:
  port: 8080

# Database Configurations
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/AuthPlus
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
#            callback url = /login/oauth2/code/google
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #            callback url = /login/oauth2/code/github
            scope:
              - user:email
              - read:user






logging:
  level:
    org.8springframework.security: DEBUG




security:
  jwt:
    secret: ${JWT_SECRET:412e2yqwfgerliu gssdjhvq8t4237r3287t34v2ro.wfea/er'fe[r['=-[iferu32yltrg34q8vr72y8iwyfterbusotvy4eprwu349843ut8934yw'-;4tu34p;-t4-5t34w=[3'[-43fu4s9efy734tr389r72093r347458tyw3490oreg45wt34546y9['/p;'/[p;l;[p/..'[p.;,90myunbtvhre65}
    issuer: ${JWT_ISSUER:securities.authplus.com}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:1800}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:3600}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http_only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}



app:
  cors:
    frontend-url: ${FRONTEND_URL:http://localhost:5173,http://localhost:3000}
  auth:
    frontend:
      login-success-redirect-uri:  ${FRONTEND_SUCCESS_URL:http://localhost:3000/refresh?returnUrl=/dashboard}
      login-failure-redirect-uri: ${FRONTEND_FAILURE_URL:http://localhost:3000/login/}